name: FastAPI Test

on:
  push:
    branches:
    - master
    
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          virtualenvs-create: false
          installer-parallel: true
      - name: Install Dependencies
        run: poetry install --no-interaction --no-root
      - name: Generate Environment Variables File
        run: |
          echo "OPENAI_TOKEN=$OPENAI_TOKEN" >> .env
          echo "DB_URL=sqlite:///./test.db" >> .env
        env:
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
      - name: Unit Testing with pytest
        run: |
          pytest